{
  "openapi": "3.0.0",
  "info": {
    "title": "Desafio - Documentando com Swagger",
    "description": "Desafio de documentação da API usando o swagger",
    "version": "1.0.0",
    "contact": "bruno@colaco.com.br"
  },
  "components": {
    "schemas": {
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        },
        "required": [
          "admin",
          "name",
          "created_at",
          "updated_at"
        ],
        "example": {
          "id": "25a3d14f-a4b5-4e47-b4e5-207580217a0f",
          "admin": false,
          "name": "John Doe",
          "email": "john.doe@email.com",
          "created_at": "2021-12-19T20:28:00.132Z",
          "updated_at": "2021-12-19T20:28:00.132Z"
        }
      }
    }
  },
  "tags": [
    {
      "name": "users",
      "description": "Gerenciador de usuários"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Cria um novo usuário",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "John Doe",
                  "email": "john.doe@email.com"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Criado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                }
              }
            }
          },
          "400": {
            "description": "Já existe um usuário com esse e-mail !",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Já existe um usuário com esse e-mail !"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Lista todos os usuários",
        "description": "Somente quem é usuário `admin` pode utilizar a rota",
        "parameters": [
          {
            "name": "user_id",
            "description": "user id",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "25a3d14f-a4b5-4e47-b4e5-207580217a0f"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação concluída com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "example": [
                  {
                    "id": "25a3d14f-a4b5-4e47-b4e5-207580217a0f",
                    "admin": false,
                    "name": "John Doe",
                    "email": "john.doe@email.com",
                    "created_at": "2021-12-19T20:28:00.132Z",
                    "updated_at": "2021-12-19T20:28:00.132Z"
                  },
                  {
                    "id": "8ff30958-831c-47cc-a621-7bf67e71f28d",
                    "admin": true,
                    "name": "Mary Doe",
                    "email": "mary.doe@email.com",
                    "created_at": "2021-12-19T20:28:00.132Z",
                    "updated_at": "2021-12-19T20:28:00.132Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Usuário não encontrado ou não tem permissão para ver !",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Usuário não encontrado ou não tem permissão para ver !"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Retorna um usuário",
        "description": "Retorna um usuário de acordo com o `id` informado",
        "parameters": [
          {
            "name": "user_id",
            "description": "user id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "25a3d14f-a4b5-4e47-b4e5-207580217a0f"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação concluída com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                }
              }
            }
          },
          "404": {
            "description": "Usuário não cadastrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Usuário não cadastrado !"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": [
          "users"
        ],
        "summary": "Tornar um usuário admin",
        "description": "Tornar um usuário, pelo seu `id`,  em  admin",
        "parameters": [
          {
            "name": "user_id",
            "description": "user id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "25a3d14f-a4b5-4e47-b4e5-207580217a0f"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operação concluída com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                },
                "example": {
                  "id": "03d00a6f-22c4-4f0f-b719-524d653b1916",
                  "admin": true,
                  "name": "Mary Doe",
                  "email": "mary.doe@email.com",
                  "created_at": "2021-12-19T20:28:00.132Z",
                  "updated_at": "2021-12-19T20:28:00.132Z"
                }
              }
            }
          },
          "404": {
            "description": "Usuário não cadastrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Usuário não cadastrado !"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}